### ISSUE TITLE
What writer should be passed to NewHandler?

### ISSUE THREAD

**Issue by paddycarver** [jussi-kalliokoski/slogdriver#2]
An end-to-end example would be really helpful. I'm not seeing an `io.Writer` defined by the `cloud.google.com/go/logging` library; what writer is expected there?

**Comment by jussi-kalliokoski** [comment]
Ah, good catch! In most cases, for example in a GKE environment that has been configured to automatically collect logs from pods, you should pass in `os.Stderr`. Does that help?

I'll leave the issue open for now as a reminbed that this basic usage example should be included in the README.

**Comment by jussi-kalliokoski** [comment]
Oh, however I should note that if you're in an environment where you need to use the HTTP logging API directly, you'll either need a bit of extra wiring that's currently not provided to pipe the log entries to the cloud logging API (supporting use cases such as that is why the `io.Writer` is accepted as a parameter rather than for example always taking `os.Stderr`), or alternatively building an entirely custom `slog.Handler` to translate `slog.Record`s into `logging.Entry`. The purpose of slogdriver is primarily to act as something that converts `slog.Record`s directly into the JSON representation of Cloud Logging's format and outputs them, using the library together with `cloud.google.com/go/logging` would have a lot of overlapping functionality and overhead (as `slogdriver` has no need for `cloud.google.com/go/logging`'s intermediate data structures).

**Comment by paddycarver** [comment]
> Oh, however I should note that if you're in an environment where you need to use the HTTP logging API directly, you'll either need a bit of extra wiring that's currently not provided to pipe the log entries to the cloud logging API

Ah! That's the bit I was missing. I misunderstood the functionality this package was implementing, and thought it talked to the HTTP logging API directly, rather than implementing the JSON format. That clarifies things considerably!
